---
- hosts: pi
  remote_user: pi
  tasks:
  - name: stop svet
    become: yes
    service:
      name: svet
      state: stopped
  - name: copy local Svet
    when: lookup('env', 'DEPLOY') != 'master'
    synchronize:
      src: '../../'
      dest: /home/pi/sve
  - name: get latet Svet
    when: lookup('env', 'DEPLOY') == 'master'
    block:
    - file: path=/home/pi/svet state=absent
    - file: path=/home/pi/svet state=directory
    - git:
        repo: 'git@github.com:iakovmarkov/svet.git'
        dest: /home/pi/svet
        accept_hostkey: yes
  - name: install packages
    npm:
      path: /home/pi/svet
  - name: start svet
    become: yes
    service:
      name: svet
      state: started
  - name: ensure svet is running
    become: yes
    service:
      name: svet
      state: started
  handlers: