---
- hosts: svet.iakov.me
  remote_user: markov
  become: yes
  tasks:
  - name: stop service
    service:
      name: svet
      state: stopped
  - name: copy local Svet
    when: lookup('env', 'DEPLOY') != 'master'
    synchronize:
      src: '../../'
      dest: /usr/bin/svet
  - name: get latet Svet
    when: lookup('env', 'DEPLOY') == 'master'
    block:
    - file: path=/usr/bin/svet state=absent
    - file: path=/usr/bin/svet state=directory
    - git:
        repo: https://github.com/iakovmarkov/svet.git
        dest: /usr/bin/svet
  - name: install packages
    command: sudo npm install
    args:
      chdir: /usr/bin/svet
  - name: start service
    service:
      name: svet
      state: started
  handlers: