const colors = [
  { color: "000080", name: "Navy Blue" },
  { color: "0000C8", name: "Dark Blue" },
  { color: "0000FF", name: "Blue" },
  { color: "000741", name: "Stratos" },
  { color: "001B1C", name: "Swamp" },
  { color: "002387", name: "Resolution Blue" },
  { color: "002900", name: "Deep Fir" },
  { color: "002E20", name: "Burnham" },
  { color: "002FA7", name: "International Klein Blue" },
  { color: "003153", name: "Prussian Blue" },
  { color: "003366", name: "Midnight Blue" },
  { color: "003399", name: "Smalt" },
  { color: "003532", name: "Deep Teal" },
  { color: "003E40", name: "Cyprus" },
  { color: "004620", name: "Kaitoke Green" },
  { color: "0047AB", name: "Cobalt" },
  { color: "004816", name: "Crusoe" },
  { color: "004950", name: "Sherpa Blue" },
  { color: "0056A7", name: "Endeavour" },
  { color: "00581A", name: "Camarone" },
  { color: "0066CC", name: "Science Blue" },
  { color: "0066FF", name: "Blue Ribbon" },
  { color: "00755E", name: "Tropical Rain Forest" },
  { color: "0076A3", name: "Allports" },
  { color: "007BA7", name: "Deep Cerulean" },
  { color: "007EC7", name: "Lochmara" },
  { color: "007FFF", name: "Azure Radiance" },
  { color: "008080", name: "Teal" },
  { color: "0095B6", name: "Bondi Blue" },
  { color: "009DC4", name: "Pacific Blue" },
  { color: "00A693", name: "Persian Green" },
  { color: "00A86B", name: "Jade" },
  { color: "00CC99", name: "Caribbean Green" },
  { color: "00CCCC", name: "Robin's Egg Blue" },
  { color: "00FF00", name: "Green" },
  { color: "00FF7F", name: "Spring Green" },
  { color: "00FFFF", name: "Cyan / Aqua" },
  { color: "010D1A", name: "Blue Charcoal" },
  { color: "011635", name: "Midnight" },
  { color: "011D13", name: "Holly" },
  { color: "012731", name: "Daintree" },
  { color: "01361C", name: "Cardin Green" },
  { color: "01371A", name: "County Green" },
  { color: "013E62", name: "Astronaut Blue" },
  { color: "013F6A", name: "Regal Blue" },
  { color: "014B43", name: "Aqua Deep" },
  { color: "015E85", name: "Orient" },
  { color: "016162", name: "Blue Stone" },
  { color: "016D39", name: "Fun Green" },
  { color: "01796F", name: "Pine Green" },
  { color: "017987", name: "Blue Lagoon" },
  { color: "01826B", name: "Deep Sea" },
  { color: "01A368", name: "Green Haze" },
  { color: "022D15", name: "English Holly" },
  { color: "02402C", name: "Sherwood Green" },
  { color: "02478E", name: "Congress Blue" },
  { color: "024E46", name: "Evening Sea" },
  { color: "026395", name: "Bahama Blue" },
  { color: "02866F", name: "Observatory" },
  { color: "02A4D3", name: "Cerulean" },
  { color: "03163C", name: "Tangaroa" },
  { color: "032B52", name: "Green Vogue" },
  { color: "036A6E", name: "Mosque" },
  { color: "041004", name: "Midnight Moss" },
  { color: "041322", name: "Black Pearl" },
  { color: "042E4C", name: "Blue Whale" },
  { color: "044022", name: "Zuccini" },
  { color: "044259", name: "Teal Blue" },
  { color: "051040", name: "Deep Cove" },
  { color: "051657", name: "Gulf Blue" },
  { color: "055989", name: "Venice Blue" },
  { color: "056F57", name: "Watercourse" },
  { color: "062A78", name: "Catalina Blue" },
  { color: "063537", name: "Tiber" },
  { color: "069B81", name: "Gossamer" },
  { color: "06A189", name: "Niagara" },
  { color: "073A50", name: "Tarawera" },
  { color: "080110", name: "Jaguar" },
  { color: "081910", name: "Black Bean" },
  { color: "082567", name: "Deep Sapphire" },
  { color: "088370", name: "Elf Green" },
  { color: "08E8DE", name: "Bright Turquoise" },
  { color: "092256", name: "Downriver" },
  { color: "09230F", name: "Palm Green" },
  { color: "09255D", name: "Madison" },
  { color: "093624", name: "Bottle Green" },
  { color: "095859", name: "Deep Sea Green" },
  { color: "097F4B", name: "Salem" },
  { color: "0A001C", name: "Black Russian" },
  { color: "0A480D", name: "Dark Fern" },
  { color: "0A6906", name: "Japanese Laurel" },
  { color: "0A6F75", name: "Atoll" },
  { color: "0B0B0B", name: "Cod Gray" },
  { color: "0B0F08", name: "Marshland" },
  { color: "0B1107", name: "Gordons Green" },
  { color: "0B1304", name: "Black Forest" },
  { color: "0B6207", name: "San Felix" },
  { color: "0BDA51", name: "Malachite" },
  { color: "0C0B1D", name: "Ebony" },
  { color: "0C0D0F", name: "Woodsmoke" },
  { color: "0C1911", name: "Racing Green" },
  { color: "0C7A79", name: "Surfie Green" },
  { color: "0C8990", name: "Blue Chill" },
  { color: "0D0332", name: "Black Rock" },
  { color: "0D1117", name: "Bunker" },
  { color: "0D1C19", name: "Aztec" },
  { color: "0D2E1C", name: "Bush" },
  { color: "0E0E18", name: "Cinder" },
  { color: "0E2A30", name: "Firefly" },
  { color: "0F2D9E", name: "Torea Bay" },
  { color: "10121D", name: "Vulcan" },
  { color: "101405", name: "Green Waterloo" },
  { color: "105852", name: "Eden" },
  { color: "110C6C", name: "Arapawa" },
  { color: "120A8F", name: "Ultramarine" },
  { color: "123447", name: "Elephant" },
  { color: "126B40", name: "Jewel" },
  { color: "130000", name: "Diesel" },
  { color: "130A06", name: "Asphalt" },
  { color: "13264D", name: "Blue Zodiac" },
  { color: "134F19", name: "Parsley" },
  { color: "140600", name: "Nero" },
  { color: "1450AA", name: "Tory Blue" },
  { color: "151F4C", name: "Bunting" },
  { color: "1560BD", name: "Denim" },
  { color: "15736B", name: "Genoa" },
  { color: "161928", name: "Mirage" },
  { color: "161D10", name: "Hunter Green" },
  { color: "162A40", name: "Big Stone" },
  { color: "163222", name: "Celtic" },
  { color: "16322C", name: "Timber Green" },
  { color: "163531", name: "Gable Green" },
  { color: "171F04", name: "Pine Tree" },
  { color: "175579", name: "Chathams Blue" },
  { color: "182D09", name: "Deep Forest Green" },
  { color: "18587A", name: "Blumine" },
  { color: "19330E", name: "Palm Leaf" },
  { color: "193751", name: "Nile Blue" },
  { color: "1959A8", name: "Fun Blue" },
  { color: "1A1A68", name: "Lucky Point" },
  { color: "1AB385", name: "Mountain Meadow" },
  { color: "1B0245", name: "Tolopea" },
  { color: "1B1035", name: "Haiti" },
  { color: "1B127B", name: "Deep Koamaru" },
  { color: "1B1404", name: "Acadia" },
  { color: "1B2F11", name: "Seaweed" },
  { color: "1B3162", name: "Biscay" },
  { color: "1B659D", name: "Matisse" },
  { color: "1C1208", name: "Crowshead" },
  { color: "1C1E13", name: "Rangoon Green" },
  { color: "1C39BB", name: "Persian Blue" },
  { color: "1C402E", name: "Everglade" },
  { color: "1C7C7D", name: "Elm" },
  { color: "1D6142", name: "Green Pea" },
  { color: "1E0F04", name: "Creole" },
  { color: "1E1609", name: "Karaka" },
  { color: "1E1708", name: "El Paso" },
  { color: "1E385B", name: "Cello" },
  { color: "1E433C", name: "Te Papa Green" },
  { color: "1E90FF", name: "Dodger Blue" },
  { color: "1E9AB0", name: "Eastern Blue" },
  { color: "1F120F", name: "Night Rider" },
  { color: "1FC2C2", name: "Java" },
  { color: "20208D", name: "Jacksons Purple" },
  { color: "202E54", name: "Cloud Burst" },
  { color: "204852", name: "Blue Dianne" },
  { color: "211A0E", name: "Eternity" },
  { color: "220878", name: "Deep Blue" },
  { color: "228B22", name: "Forest Green" },
  { color: "233418", name: "Mallard" },
  { color: "240A40", name: "Violet" },
  { color: "240C02", name: "Kilamanjaro" },
  { color: "242A1D", name: "Log Cabin" },
  { color: "242E16", name: "Black Olive" },
  { color: "24500F", name: "Green House" },
  { color: "251607", name: "Graphite" },
  { color: "251706", name: "Cannon Black" },
  { color: "251F4F", name: "Port Gore" },
  { color: "25272C", name: "Shark" },
  { color: "25311C", name: "Green Kelp" },
  { color: "2596D1", name: "Curious Blue" },
  { color: "260368", name: "Paua" },
  { color: "26056A", name: "Paris M" },
  { color: "261105", name: "Wood Bark" },
  { color: "261414", name: "Gondola" },
  { color: "262335", name: "Steel Gray" },
  { color: "26283B", name: "Ebony Clay" },
  { color: "273A81", name: "Bay of Many" },
  { color: "27504B", name: "Plantation" },
  { color: "278A5B", name: "Eucalyptus" },
  { color: "281E15", name: "Oil" },
  { color: "283A77", name: "Astronaut" },
  { color: "286ACD", name: "Mariner" },
  { color: "290C5E", name: "Violent Violet" },
  { color: "292130", name: "Bastille" },
  { color: "292319", name: "Zeus" },
  { color: "292937", name: "Charade" },
  { color: "297B9A", name: "Jelly Bean" },
  { color: "29AB87", name: "Jungle Green" },
  { color: "2A0359", name: "Cherry Pie" },
  { color: "2A140E", name: "Coffee Bean" },
  { color: "2A2630", name: "Baltic Sea" },
  { color: "2A380B", name: "Turtle Green" },
  { color: "2A52BE", name: "Cerulean Blue" },
  { color: "2B0202", name: "Sepia Black" },
  { color: "2B194F", name: "Valhalla" },
  { color: "2B3228", name: "Heavy Metal" },
  { color: "2C0E8C", name: "Blue Gem" },
  { color: "2C1632", name: "Revolver" },
  { color: "2C2133", name: "Bleached Cedar" },
  { color: "2C8C84", name: "Lochinvar" },
  { color: "2D2510", name: "Mikado" },
  { color: "2D383A", name: "Outer Space" },
  { color: "2D569B", name: "St Tropaz" },
  { color: "2E0329", name: "Jacaranda" },
  { color: "2E1905", name: "Jacko Bean" },
  { color: "2E3222", name: "Rangitoto" },
  { color: "2E3F62", name: "Rhino" },
  { color: "2E8B57", name: "Sea Green" },
  { color: "2EBFD4", name: "Scooter" },
  { color: "2F270E", name: "Onion" },
  { color: "2F3CB3", name: "Governor Bay" },
  { color: "2F519E", name: "Sapphire" },
  { color: "2F5A57", name: "Spectra" },
  { color: "2F6168", name: "Casal" },
  { color: "300529", name: "Melanzane" },
  { color: "301F1E", name: "Cocoa Brown" },
  { color: "302A0F", name: "Woodrush" },
  { color: "304B6A", name: "San Juan" },
  { color: "30D5C8", name: "Turquoise" },
  { color: "311C17", name: "Eclipse" },
  { color: "314459", name: "Pickled Bluewood" },
  { color: "315BA1", name: "Azure" },
  { color: "31728D", name: "Calypso" },
  { color: "317D82", name: "Paradiso" },
  { color: "32127A", name: "Persian Indigo" },
  { color: "32293A", name: "Blackcurrant" },
  { color: "323232", name: "Mine Shaft" },
  { color: "325D52", name: "Stromboli" },
  { color: "327C14", name: "Bilbao" },
  { color: "327DA0", name: "Astral" },
  { color: "33036B", name: "Christalle" },
  { color: "33292F", name: "Thunder" },
  { color: "33CC99", name: "Shamrock" },
  { color: "341515", name: "Tamarind" },
  { color: "350036", name: "Mardi Gras" },
  { color: "350E42", name: "Valentino" },
  { color: "350E57", name: "Jagger" },
  { color: "353542", name: "Tuna" },
  { color: "354E8C", name: "Chambray" },
  { color: "363050", name: "Martinique" },
  { color: "363534", name: "Tuatara" },
  { color: "363C0D", name: "Waiouru" },
  { color: "36747D", name: "Ming" },
  { color: "368716", name: "La Palma" },
  { color: "370202", name: "Chocolate" },
  { color: "371D09", name: "Clinker" },
  { color: "37290E", name: "Brown Tumbleweed" },
  { color: "373021", name: "Birch" },
  { color: "377475", name: "Oracle" },
  { color: "380474", name: "Blue Diamond" },
  { color: "381A51", name: "Grape" },
  { color: "383533", name: "Dune" },
  { color: "384555", name: "Oxford Blue" },
  { color: "384910", name: "Clover" },
  { color: "394851", name: "Limed Spruce" },
  { color: "396413", name: "Dell" },
  { color: "3A0020", name: "Toledo" },
  { color: "3A2010", name: "Sambuca" },
  { color: "3A2A6A", name: "Jacarta" },
  { color: "3A686C", name: "William" },
  { color: "3A6A47", name: "Killarney" },
  { color: "3AB09E", name: "Keppel" },
  { color: "3B000B", name: "Temptress" },
  { color: "3B0910", name: "Aubergine" },
  { color: "3B1F1F", name: "Jon" },
  { color: "3B2820", name: "Treehouse" },
  { color: "3B7A57", name: "Amazon" },
  { color: "3B91B4", name: "Boston Blue" },
  { color: "3C0878", name: "Windsor" },
  { color: "3C1206", name: "Rebel" },
  { color: "3C1F76", name: "Meteorite" },
  { color: "3C2005", name: "Dark Ebony" },
  { color: "3C3910", name: "Camouflage" },
  { color: "3C4151", name: "Bright Gray" },
  { color: "3C4443", name: "Cape Cod" },
  { color: "3C493A", name: "Lunar Green" },
  { color: "3D0C02", name: "Bean  " },
  { color: "3D2B1F", name: "Bistre" },
  { color: "3D7D52", name: "Goblin" },
  { color: "3E0480", name: "Kingfisher Daisy" },
  { color: "3E1C14", name: "Cedar" },
  { color: "3E2B23", name: "English Walnut" },
  { color: "3E2C1C", name: "Black Marlin" },
  { color: "3E3A44", name: "Ship Gray" },
  { color: "3EABBF", name: "Pelorous" },
  { color: "3F2109", name: "Bronze" },
  { color: "3F2500", name: "Cola" },
  { color: "3F3002", name: "Madras" },
  { color: "3F307F", name: "Minsk" },
  { color: "3F4C3A", name: "Cabbage Pont" },
  { color: "3F583B", name: "Tom Thumb" },
  { color: "3F5D53", name: "Mineral Green" },
  { color: "3FC1AA", name: "Puerto Rico" },
  { color: "3FFF00", name: "Harlequin" },
  { color: "401801", name: "Brown Pod" },
  { color: "40291D", name: "Cork" },
  { color: "403B38", name: "Masala" },
  { color: "403D19", name: "Thatch Green" },
  { color: "405169", name: "Fiord" },
  { color: "40826D", name: "Viridian" },
  { color: "40A860", name: "Chateau Green" },
  { color: "410056", name: "Ripe Plum" },
  { color: "411F10", name: "Paco" },
  { color: "412010", name: "Deep Oak" },
  { color: "413C37", name: "Merlin" },
  { color: "414257", name: "Gun Powder" },
  { color: "414C7D", name: "East Bay" },
  { color: "4169E1", name: "Royal Blue" },
  { color: "41AA78", name: "Ocean Green" },
  { color: "420303", name: "Burnt Maroon" },
  { color: "423921", name: "Lisbon Brown" },
  { color: "427977", name: "Faded Jade" },
  { color: "431560", name: "Scarlet Gum" },
  { color: "433120", name: "Iroko" },
  { color: "433E37", name: "Armadillo" },
  { color: "434C59", name: "River Bed" },
  { color: "436A0D", name: "Green Leaf" },
  { color: "44012D", name: "Barossa" },
  { color: "441D00", name: "Morocco Brown" },
  { color: "444954", name: "Mako" },
  { color: "454936", name: "Kelp" },
  { color: "456CAC", name: "San Marino" },
  { color: "45B1E8", name: "Picton Blue" },
  { color: "460B41", name: "Loulou" },
  { color: "462425", name: "Crater Brown" },
  { color: "465945", name: "Gray Asparagus" },
  { color: "4682B4", name: "Steel Blue" },
  { color: "480404", name: "Rustic Red" },
  { color: "480607", name: "Bulgarian Rose" },
  { color: "480656", name: "Clairvoyant" },
  { color: "481C1C", name: "Cocoa Bean" },
  { color: "483131", name: "Woody Brown" },
  { color: "483C32", name: "Taupe" },
  { color: "49170C", name: "Van Cleef" },
  { color: "492615", name: "Brown Derby" },
  { color: "49371B", name: "Metallic Bronze" },
  { color: "495400", name: "Verdun Green" },
  { color: "496679", name: "Blue Bayoux" },
  { color: "497183", name: "Bismark" },
  { color: "4A2A04", name: "Bracken" },
  { color: "4A3004", name: "Deep Bronze" },
  { color: "4A3C30", name: "Mondo" },
  { color: "4A4244", name: "Tundora" },
  { color: "4A444B", name: "Gravel" },
  { color: "4A4E5A", name: "Trout" },
  { color: "4B0082", name: "Pigment Indigo" },
  { color: "4B5D52", name: "Nandor" },
  { color: "4C3024", name: "Saddle" },
  { color: "4C4F56", name: "Abbey" },
  { color: "4D0135", name: "Blackberry" },
  { color: "4D0A18", name: "Cab Sav" },
  { color: "4D1E01", name: "Indian Tan" },
  { color: "4D282D", name: "Cowboy" },
  { color: "4D282E", name: "Livid Brown" },
  { color: "4D3833", name: "Rock" },
  { color: "4D3D14", name: "Punga" },
  { color: "4D400F", name: "Bronzetone" },
  { color: "4D5328", name: "Woodland" },
  { color: "4E0606", name: "Mahogany" },
  { color: "4E2A5A", name: "Bossanova" },
  { color: "4E3B41", name: "Matterhorn" },
  { color: "4E420C", name: "Bronze Olive" },
  { color: "4E4562", name: "Mulled Wine" },
  { color: "4E6649", name: "Axolotl" },
  { color: "4E7F9E", name: "Wedgewood" },
  { color: "4EABD1", name: "Shakespeare" },
  { color: "4F1C70", name: "Honey Flower" },
  { color: "4F2398", name: "Daisy Bush" },
  { color: "4F69C6", name: "Indigo" },
  { color: "4F7942", name: "Fern Green" },
  { color: "4F9D5D", name: "Fruit Salad" },
  { color: "4FA83D", name: "Apple" },
  { color: "504351", name: "Mortar" },
  { color: "507096", name: "Kashmir Blue" },
  { color: "507672", name: "Cutty Sark" },
  { color: "50C878", name: "Emerald" },
  { color: "514649", name: "Emperor" },
  { color: "516E3D", name: "Chalet Green" },
  { color: "517C66", name: "Como" },
  { color: "51808F", name: "Smalt Blue" },
  { color: "52001F", name: "Castro" },
  { color: "520C17", name: "Maroon Oak" },
  { color: "523C94", name: "Gigas" },
  { color: "533455", name: "Voodoo" },
  { color: "534491", name: "Victoria" },
  { color: "53824B", name: "Hippie Green" },
  { color: "541012", name: "Heath" },
  { color: "544333", name: "Judge Gray" },
  { color: "54534D", name: "Fuscous Gray" },
  { color: "549019", name: "Vida Loca" },
  { color: "55280C", name: "Cioccolato" },
  { color: "555B10", name: "Saratoga" },
  { color: "556D56", name: "Finlandia" },
  { color: "5590D9", name: "Havelock Blue" },
  { color: "56B4BE", name: "Fountain Blue" },
  { color: "578363", name: "Spring Leaves" },
  { color: "583401", name: "Saddle Brown" },
  { color: "585562", name: "Scarpa Flow" },
  { color: "587156", name: "Cactus" },
  { color: "589AAF", name: "Hippie Blue" },
  { color: "591D35", name: "Wine Berry" },
  { color: "592804", name: "Brown Bramble" },
  { color: "593737", name: "Congo Brown" },
  { color: "594433", name: "Millbrook" },
  { color: "5A6E9C", name: "Waikawa Gray" },
  { color: "5A87A0", name: "Horizon" },
  { color: "5B3013", name: "Jambalaya" },
  { color: "5C0120", name: "Bordeaux" },
  { color: "5C0536", name: "Mulberry Wood" },
  { color: "5C2E01", name: "Carnaby Tan" },
  { color: "5C5D75", name: "Comet" },
  { color: "5D1E0F", name: "Redwood" },
  { color: "5D4C51", name: "Don Juan" },
  { color: "5D5C58", name: "Chicago" },
  { color: "5D5E37", name: "Verdigris" },
  { color: "5D7747", name: "Dingley" },
  { color: "5DA19F", name: "Breaker Bay" },
  { color: "5E483E", name: "Kabul" },
  { color: "5E5D3B", name: "Hemlock" },
  { color: "5F3D26", name: "Irish Coffee" },
  { color: "5F5F6E", name: "Mid Gray" },
  { color: "5F6672", name: "Shuttle Gray" },
  { color: "5FA777", name: "Aqua Forest" },
  { color: "5FB3AC", name: "Tradewind" },
  { color: "604913", name: "Horses Neck" },
  { color: "605B73", name: "Smoky" },
  { color: "606E68", name: "Corduroy" },
  { color: "6093D1", name: "Danube" },
  { color: "612718", name: "Espresso" },
  { color: "614051", name: "Eggplant" },
  { color: "615D30", name: "Costa Del Sol" },
  { color: "61845F", name: "Glade Green" },
  { color: "622F30", name: "Buccaneer" },
  { color: "623F2D", name: "Quincy" },
  { color: "624E9A", name: "Butterfly Bush" },
  { color: "625119", name: "West Coast" },
  { color: "626649", name: "Finch" },
  { color: "639A8F", name: "Patina" },
  { color: "63B76C", name: "Fern" },
  { color: "6456B7", name: "Blue Violet" },
  { color: "646077", name: "Dolphin" },
  { color: "646463", name: "Storm Dust" },
  { color: "646A54", name: "Siam" },
  { color: "646E75", name: "Nevada" },
  { color: "6495ED", name: "Cornflower Blue" },
  { color: "64CCDB", name: "Viking" },
  { color: "65000B", name: "Rosewood" },
  { color: "651A14", name: "Cherrywood" },
  { color: "652DC1", name: "Purple Heart" },
  { color: "657220", name: "Fern Frond" },
  { color: "65745D", name: "Willow Grove" },
  { color: "65869F", name: "Hoki" },
  { color: "660045", name: "Pompadour" },
  { color: "660099", name: "Purple" },
  { color: "66023C", name: "Tyrian Purple" },
  { color: "661010", name: "Dark Tan" },
  { color: "66B58F", name: "Silver Tree" },
  { color: "66FF00", name: "Bright Green" },
  { color: "66FF66", name: "Screamin' Green" },
  { color: "67032D", name: "Black Rose" },
  { color: "675FA6", name: "Scampi" },
  { color: "676662", name: "Ironside Gray" },
  { color: "678975", name: "Viridian Green" },
  { color: "67A712", name: "Christi" },
  { color: "683600", name: "Nutmeg Wood Finish" },
  { color: "685558", name: "Zambezi" },
  { color: "685E6E", name: "Salt Box" },
  { color: "692545", name: "Tawny Port" },
  { color: "692D54", name: "Finn" },
  { color: "695F62", name: "Scorpion" },
  { color: "697E9A", name: "Lynch" },
  { color: "6A442E", name: "Spice" },
  { color: "6A5D1B", name: "Himalaya" },
  { color: "6A6051", name: "Soya Bean" },
  { color: "6B2A14", name: "Hairy Heath" },
  { color: "6B3FA0", name: "Royal Purple" },
  { color: "6B4E31", name: "Shingle Fawn" },
  { color: "6B5755", name: "Dorado" },
  { color: "6B8BA2", name: "Bermuda Gray" },
  { color: "6B8E23", name: "Olive Drab" },
  { color: "6C3082", name: "Eminence" },
  { color: "6CDAE7", name: "Turquoise Blue" },
  { color: "6D0101", name: "Lonestar" },
  { color: "6D5E54", name: "Pine Cone" },
  { color: "6D6C6C", name: "Dove Gray" },
  { color: "6D9292", name: "Juniper" },
  { color: "6D92A1", name: "Gothic" },
  { color: "6E0902", name: "Red Oxide" },
  { color: "6E1D14", name: "Moccaccino" },
  { color: "6E4826", name: "Pickled Bean" },
  { color: "6E4B26", name: "Dallas" },
  { color: "6E6D57", name: "Kokoda" },
  { color: "6E7783", name: "Pale Sky" },
  { color: "6F440C", name: "Cafe Royale" },
  { color: "6F6A61", name: "Flint" },
  { color: "6F8E63", name: "Highland" },
  { color: "6F9D02", name: "Limeade" },
  { color: "6FD0C5", name: "Downy" },
  { color: "701C1C", name: "Persian Plum" },
  { color: "704214", name: "Sepia" },
  { color: "704A07", name: "Antique Bronze" },
  { color: "704F50", name: "Ferra" },
  { color: "706555", name: "Coffee" },
  { color: "708090", name: "Slate Gray" },
  { color: "711A00", name: "Cedar Wood Finish" },
  { color: "71291D", name: "Metallic Copper" },
  { color: "714693", name: "Affair" },
  { color: "714AB2", name: "Studio" },
  { color: "715D47", name: "Tobacco Brown" },
  { color: "716338", name: "Yellow Metal" },
  { color: "716B56", name: "Peat" },
  { color: "716E10", name: "Olivetone" },
  { color: "717486", name: "Storm Gray" },
  { color: "718080", name: "Sirocco" },
  { color: "71D9E2", name: "Aquamarine Blue" },
  { color: "72010F", name: "Venetian Red" },
  { color: "724A2F", name: "Old Copper" },
  { color: "726D4E", name: "Go Ben" },
  { color: "727B89", name: "Raven" },
  { color: "731E8F", name: "Seance" },
  { color: "734A12", name: "Raw Umber" },
  { color: "736C9F", name: "Kimberly" },
  { color: "736D58", name: "Crocodile" },
  { color: "737829", name: "Crete" },
  { color: "738678", name: "Xanadu" },
  { color: "74640D", name: "Spicy Mustard" },
  { color: "747D63", name: "Limed Ash" },
  { color: "747D83", name: "Rolling Stone" },
  { color: "748881", name: "Blue Smoke" },
  { color: "749378", name: "Laurel" },
  { color: "74C365", name: "Mantis" },
  { color: "755A57", name: "Russett" },
  { color: "7563A8", name: "Deluge" },
  { color: "76395D", name: "Cosmic" },
  { color: "7666C6", name: "Blue Marguerite" },
  { color: "76BD17", name: "Lima" },
  { color: "76D7EA", name: "Sky Blue" },
  { color: "770F05", name: "Dark Burgundy" },
  { color: "771F1F", name: "Crown of Thorns" },
  { color: "773F1A", name: "Walnut" },
  { color: "776F61", name: "Pablo" },
  { color: "778120", name: "Pacifika" },
  { color: "779E86", name: "Oxley" },
  { color: "77DD77", name: "Pastel Green" },
  { color: "780109", name: "Japanese Maple" },
  { color: "782D19", name: "Mocha" },
  { color: "782F16", name: "Peanut" },
  { color: "78866B", name: "Camouflage Green" },
  { color: "788A25", name: "Wasabi" },
  { color: "788BBA", name: "Ship Cove" },
  { color: "78A39C", name: "Sea Nymph" },
  { color: "795D4C", name: "Roman Coffee" },
  { color: "796878", name: "Old Lavender" },
  { color: "796989", name: "Rum" },
  { color: "796A78", name: "Fedora" },
  { color: "796D62", name: "Sandstone" },
  { color: "79DEEC", name: "Spray" },
  { color: "7A013A", name: "Siren" },
  { color: "7A58C1", name: "Fuchsia Blue" },
  { color: "7A7A7A", name: "Boulder" },
  { color: "7A89B8", name: "Wild Blue Yonder" },
  { color: "7AC488", name: "De York" },
  { color: "7B3801", name: "Red Beech" },
  { color: "7B3F00", name: "Cinnamon" },
  { color: "7B6608", name: "Yukon Gold" },
  { color: "7B7874", name: "Tapa" },
  { color: "7B7C94", name: "Waterloo " },
  { color: "7B8265", name: "Flax Smoke" },
  { color: "7B9F80", name: "Amulet" },
  { color: "7BA05B", name: "Asparagus" },
  { color: "7C1C05", name: "Kenyan Copper" },
  { color: "7C7631", name: "Pesto" },
  { color: "7C778A", name: "Topaz" },
  { color: "7C7B7A", name: "Concord" },
  { color: "7C7B82", name: "Jumbo" },
  { color: "7C881A", name: "Trendy Green" },
  { color: "7CA1A6", name: "Gumbo" },
  { color: "7CB0A1", name: "Acapulco" },
  { color: "7CB7BB", name: "Neptune" },
  { color: "7D2C14", name: "Pueblo" },
  { color: "7DA98D", name: "Bay Leaf" },
  { color: "7DC8F7", name: "Malibu" },
  { color: "7DD8C6", name: "Bermuda" },
  { color: "7E3A15", name: "Copper Canyon" },
  { color: "7F1734", name: "Claret" },
  { color: "7F3A02", name: "Peru Tan" },
  { color: "7F626D", name: "Falcon" },
  { color: "7F7589", name: "Mobster" },
  { color: "7F76D3", name: "Moody Blue" },
  { color: "7FFF00", name: "Chartreuse" },
  { color: "7FFFD4", name: "Aquamarine" },
  { color: "800000", name: "Maroon" },
  { color: "800B47", name: "Rose Bud Cherry" },
  { color: "801818", name: "Falu Red" },
  { color: "80341F", name: "Red Robin" },
  { color: "803790", name: "Vivid Violet" },
  { color: "80461B", name: "Russet" },
  { color: "807E79", name: "Friar Gray" },
  { color: "808000", name: "Olive" },
  { color: "808080", name: "Gray" },
  { color: "80B3AE", name: "Gulf Stream" },
  { color: "80B3C4", name: "Glacier" },
  { color: "80CCEA", name: "Seagull" },
  { color: "81422C", name: "Nutmeg" },
  { color: "816E71", name: "Spicy Pink" },
  { color: "817377", name: "Empress" },
  { color: "819885", name: "Spanish Green" },
  { color: "826F65", name: "Sand Dune" },
  { color: "828685", name: "Gunsmoke" },
  { color: "828F72", name: "Battleship Gray" },
  { color: "831923", name: "Merlot" },
  { color: "837050", name: "Shadow" },
  { color: "83AA5D", name: "Chelsea Cucumber" },
  { color: "83D0C6", name: "Monte Carlo" },
  { color: "843179", name: "Plum" },
  { color: "84A0A0", name: "Granny Smith" },
  { color: "8581D9", name: "Chetwode Blue" },
  { color: "858470", name: "Bandicoot" },
  { color: "859FAF", name: "Bali Hai" },
  { color: "85C4CC", name: "Half Baked" },
  { color: "860111", name: "Red Devil" },
  { color: "863C3C", name: "Lotus" },
  { color: "86483C", name: "Ironstone" },
  { color: "864D1E", name: "Bull Shot" },
  { color: "86560A", name: "Rusty Nail" },
  { color: "868974", name: "Bitter" },
  { color: "86949F", name: "Regent Gray" },
  { color: "871550", name: "Disco" },
  { color: "87756E", name: "Americano" },
  { color: "877C7B", name: "Hurricane" },
  { color: "878D91", name: "Oslo Gray" },
  { color: "87AB39", name: "Sushi" },
  { color: "885342", name: "Spicy Mix" },
  { color: "886221", name: "Kumera" },
  { color: "888387", name: "Suva Gray" },
  { color: "888D65", name: "Avocado" },
  { color: "893456", name: "Camelot" },
  { color: "893843", name: "Solid Pink" },
  { color: "894367", name: "Cannon Pink" },
  { color: "897D6D", name: "Makara" },
  { color: "8A3324", name: "Burnt Umber" },
  { color: "8A73D6", name: "True V" },
  { color: "8A8360", name: "Clay Creek" },
  { color: "8A8389", name: "Monsoon" },
  { color: "8A8F8A", name: "Stack" },
  { color: "8AB9F1", name: "Jordy Blue" },
  { color: "8B00FF", name: "Electric Violet" },
  { color: "8B0723", name: "Monarch" },
  { color: "8B6B0B", name: "Corn Harvest" },
  { color: "8B8470", name: "Olive Haze" },
  { color: "8B847E", name: "Schooner" },
  { color: "8B8680", name: "Natural Gray" },
  { color: "8B9C90", name: "Mantle" },
  { color: "8B9FEE", name: "Portage" },
  { color: "8BA690", name: "Envy" },
  { color: "8BA9A5", name: "Cascade" },
  { color: "8BE6D8", name: "Riptide" },
  { color: "8C055E", name: "Cardinal Pink" },
  { color: "8C472F", name: "Mule Fawn" },
  { color: "8C5738", name: "Potters Clay" },
  { color: "8C6495", name: "Trendy Pink" },
  { color: "8D0226", name: "Paprika" },
  { color: "8D3D38", name: "Sanguine Brown" },
  { color: "8D3F3F", name: "Tosca" },
  { color: "8D7662", name: "Cement" },
  { color: "8D8974", name: "Granite Green" },
  { color: "8D90A1", name: "Manatee" },
  { color: "8DA8CC", name: "Polo Blue" },
  { color: "8E0000", name: "Red Berry" },
  { color: "8E4D1E", name: "Rope" },
  { color: "8E6F70", name: "Opium" },
  { color: "8E775E", name: "Domino" },
  { color: "8E8190", name: "Mamba" },
  { color: "8EABC1", name: "Nepal" },
  { color: "8F021C", name: "Pohutukawa" },
  { color: "8F3E33", name: "El Salva" },
  { color: "8F4B0E", name: "Korma" },
  { color: "8F8176", name: "Squirrel" },
  { color: "8FD6B4", name: "Vista Blue" },
  { color: "900020", name: "Burgundy" },
  { color: "901E1E", name: "Old Brick" },
  { color: "907874", name: "Hemp" },
  { color: "907B71", name: "Almond Frost" },
  { color: "908D39", name: "Sycamore" },
  { color: "92000A", name: "Sangria" },
  { color: "924321", name: "Cumin" },
  { color: "926F5B", name: "Beaver" },
  { color: "928573", name: "Stonewall" },
  { color: "928590", name: "Venus" },
  { color: "9370DB", name: "Medium Purple" },
  { color: "93CCEA", name: "Cornflower" },
  { color: "93DFB8", name: "Algae Green" },
  { color: "944747", name: "Copper Rust" },
  { color: "948771", name: "Arrowtown" },
  { color: "950015", name: "Scarlett" },
  { color: "956387", name: "Strikemaster" },
  { color: "959396", name: "Mountain Mist" },
  { color: "960018", name: "Carmine" },
  { color: "964B00", name: "Brown" },
  { color: "967059", name: "Leather" },
  { color: "9678B6", name: "Purple Mountain's Majesty" },
  { color: "967BB6", name: "Lavender Purple" },
  { color: "96A8A1", name: "Pewter" },
  { color: "96BBAB", name: "Summer Green" },
  { color: "97605D", name: "Au Chico" },
  { color: "9771B5", name: "Wisteria" },
  { color: "97CD2D", name: "Atlantis" },
  { color: "983D61", name: "Vin Rouge" },
  { color: "9874D3", name: "Lilac Bush" },
  { color: "98777B", name: "Bazaar" },
  { color: "98811B", name: "Hacienda" },
  { color: "988D77", name: "Pale Oyster" },
  { color: "98FF98", name: "Mint Green" },
  { color: "990066", name: "Fresh Eggplant" },
  { color: "991199", name: "Violet Eggplant" },
  { color: "991613", name: "Tamarillo" },
  { color: "991B07", name: "Totem Pole" },
  { color: "996666", name: "Copper Rose" },
  { color: "9966CC", name: "Amethyst" },
  { color: "997A8D", name: "Mountbatten Pink" },
  { color: "9999CC", name: "Blue Bell" },
  { color: "9A3820", name: "Prairie Sand" },
  { color: "9A6E61", name: "Toast" },
  { color: "9A9577", name: "Gurkha" },
  { color: "9AB973", name: "Olivine" },
  { color: "9AC2B8", name: "Shadow Green" },
  { color: "9B4703", name: "Oregon" },
  { color: "9B9E8F", name: "Lemon Grass" },
  { color: "9C3336", name: "Stiletto" },
  { color: "9D5616", name: "Hawaiian Tan" },
  { color: "9DACB7", name: "Gull Gray" },
  { color: "9DC209", name: "Pistachio" },
  { color: "9DE093", name: "Granny Smith Apple" },
  { color: "9DE5FF", name: "Anakiwa" },
  { color: "9E5302", name: "Chelsea Gem" },
  { color: "9E5B40", name: "Sepia Skin" },
  { color: "9EA587", name: "Sage" },
  { color: "9EA91F", name: "Citron" },
  { color: "9EB1CD", name: "Rock Blue" },
  { color: "9EDEE0", name: "Morning Glory" },
  { color: "9F381D", name: "Cognac" },
  { color: "9F821C", name: "Reef Gold" },
  { color: "9F9F9C", name: "Star Dust" },
  { color: "9FA0B1", name: "Santas Gray" },
  { color: "9FD7D3", name: "Sinbad" },
  { color: "9FDD8C", name: "Feijoa" },
  { color: "A02712", name: "Tabasco" },
  { color: "A1750D", name: "Buttered Rum" },
  { color: "A1ADB5", name: "Hit Gray" },
  { color: "A1C50A", name: "Citrus" },
  { color: "A1DAD7", name: "Aqua Island" },
  { color: "A1E9DE", name: "Water Leaf" },
  { color: "A2006D", name: "Flirt" },
  { color: "A23B6C", name: "Rouge" },
  { color: "A26645", name: "Cape Palliser" },
  { color: "A2AAB3", name: "Gray Chateau" },
  { color: "A2AEAB", name: "Edward" },
  { color: "A3807B", name: "Pharlap" },
  { color: "A397B4", name: "Amethyst Smoke" },
  { color: "A3E3ED", name: "Blizzard Blue" },
  { color: "A4A49D", name: "Delta" },
  { color: "A4A6D3", name: "Wistful" },
  { color: "A4AF6E", name: "Green Smoke" },
  { color: "A50B5E", name: "Jazzberry Jam" },
  { color: "A59B91", name: "Zorba" },
  { color: "A5CB0C", name: "Bahia" },
  { color: "A62F20", name: "Roof Terracotta" },
  { color: "A65529", name: "Paarl" },
  { color: "A68B5B", name: "Barley Corn" },
  { color: "A69279", name: "Donkey Brown" },
  { color: "A6A29A", name: "Dawn" },
  { color: "A72525", name: "Mexican Red" },
  { color: "A7882C", name: "Luxor Gold" },
  { color: "A85307", name: "Rich Gold" },
  { color: "A86515", name: "Reno Sand" },
  { color: "A86B6B", name: "Coral Tree" },
  { color: "A8989B", name: "Dusty Gray" },
  { color: "A899E6", name: "Dull Lavender" },
  { color: "A8A589", name: "Tallow" },
  { color: "A8AE9C", name: "Bud" },
  { color: "A8AF8E", name: "Locust" },
  { color: "A8BD9F", name: "Norway" },
  { color: "A8E3BD", name: "Chinook" },
  { color: "A9A491", name: "Gray Olive" },
  { color: "A9ACB6", name: "Aluminium" },
  { color: "A9B2C3", name: "Cadet Blue" },
  { color: "A9B497", name: "Schist" },
  { color: "A9BDBF", name: "Tower Gray" },
  { color: "A9BEF2", name: "Perano" },
  { color: "A9C6C2", name: "Opal" },
  { color: "AA375A", name: "Night Shadz" },
  { color: "AA4203", name: "Fire" },
  { color: "AA8B5B", name: "Muesli" },
  { color: "AA8D6F", name: "Sandal" },
  { color: "AAA5A9", name: "Shady Lady" },
  { color: "AAA9CD", name: "Logan" },
  { color: "AAABB7", name: "Spun Pearl" },
  { color: "AAD6E6", name: "Regent St Blue" },
  { color: "AAF0D1", name: "Magic Mint" },
  { color: "AB0563", name: "Lipstick" },
  { color: "AB3472", name: "Royal Heath" },
  { color: "AB917A", name: "Sandrift" },
  { color: "ABA0D9", name: "Cold Purple" },
  { color: "ABA196", name: "Bronco" },
  { color: "AC8A56", name: "Limed Oak" },
  { color: "AC91CE", name: "East Side" },
  { color: "AC9E22", name: "Lemon Ginger" },
  { color: "ACA494", name: "Napa" },
  { color: "ACA586", name: "Hillary" },
  { color: "ACA59F", name: "Cloudy" },
  { color: "ACACAC", name: "Silver Chalice" },
  { color: "ACB78E", name: "Swamp Green" },
  { color: "ACCBB1", name: "Spring Rain" },
  { color: "ACDD4D", name: "Conifer" },
  { color: "ACE1AF", name: "Celadon" },
  { color: "AD781B", name: "Mandalay" },
  { color: "ADBED1", name: "Casper" },
  { color: "ADDFAD", name: "Moss Green" },
  { color: "ADE6C4", name: "Padua" },
  { color: "ADFF2F", name: "Green Yellow" },
  { color: "AE4560", name: "Hippie Pink" },
  { color: "AE6020", name: "Desert" },
  { color: "AE809E", name: "Bouquet" },
  { color: "AF4035", name: "Medium Carmine" },
  { color: "AF4D43", name: "Apple Blossom" },
  { color: "AF593E", name: "Brown Rust" },
  { color: "AF8751", name: "Driftwood" },
  { color: "AF8F2C", name: "Alpine" },
  { color: "AF9F1C", name: "Lucky" },
  { color: "AFA09E", name: "Martini" },
  { color: "AFB1B8", name: "Bombay" },
  { color: "AFBDD9", name: "Pigeon Post" },
  { color: "B04C6A", name: "Cadillac" },
  { color: "B05D54", name: "Matrix" },
  { color: "B05E81", name: "Tapestry" },
  { color: "B06608", name: "Mai Tai" },
  { color: "B09A95", name: "Del Rio" },
  { color: "B0E0E6", name: "Powder Blue" },
  { color: "B0E313", name: "Inch Worm" },
  { color: "B10000", name: "Bright Red" },
  { color: "B14A0B", name: "Vesuvius" },
  { color: "B1610B", name: "Pumpkin Skin" },
  { color: "B16D52", name: "Santa Fe" },
  { color: "B19461", name: "Teak" },
  { color: "B1E2C1", name: "Fringy Flower" },
  { color: "B1F4E7", name: "Ice Cold" },
  { color: "B20931", name: "Shiraz" },
  { color: "B2A1EA", name: "Biloba Flower" },
  { color: "B32D29", name: "Tall Poppy" },
  { color: "B35213", name: "Fiery Orange" },
  { color: "B38007", name: "Hot Toddy" },
  { color: "B3AF95", name: "Taupe Gray" },
  { color: "B3C110", name: "La Rioja" },
  { color: "B43332", name: "Well Read" },
  { color: "B44668", name: "Blush" },
  { color: "B4CFD3", name: "Jungle Mist" },
  { color: "B57281", name: "Turkish Rose" },
  { color: "B57EDC", name: "Lavender" },
  { color: "B5A27F", name: "Mongoose" },
  { color: "B5B35C", name: "Olive Green" },
  { color: "B5D2CE", name: "Jet Stream" },
  { color: "B5ECDF", name: "Cruise" },
  { color: "B6316C", name: "Hibiscus" },
  { color: "B69D98", name: "Thatch" },
  { color: "B6B095", name: "Heathered Gray" },
  { color: "B6BAA4", name: "Eagle" },
  { color: "B6D1EA", name: "Spindle" },
  { color: "B6D3BF", name: "Gum Leaf" },
  { color: "B7410E", name: "Rust" },
  { color: "B78E5C", name: "Muddy Waters" },
  { color: "B7A214", name: "Sahara" },
  { color: "B7A458", name: "Husk" },
  { color: "B7B1B1", name: "Nobel" },
  { color: "B7C3D0", name: "Heather" },
  { color: "B7F0BE", name: "Madang" },
  { color: "B81104", name: "Milano Red" },
  { color: "B87333", name: "Copper" },
  { color: "B8B56A", name: "Gimblet" },
  { color: "B8C1B1", name: "Green Spring" },
  { color: "B8C25D", name: "Celery" },
  { color: "B8E0F9", name: "Sail" },
  { color: "B94E48", name: "Chestnut" },
  { color: "B95140", name: "Crail" },
  { color: "B98D28", name: "Marigold" },
  { color: "B9C46A", name: "Wild Willow" },
  { color: "B9C8AC", name: "Rainee" },
  { color: "BA0101", name: "Guardsman Red" },
  { color: "BA450C", name: "Rock Spray" },
  { color: "BA6F1E", name: "Bourbon" },
  { color: "BA7F03", name: "Pirate Gold" },
  { color: "BAB1A2", name: "Nomad" },
  { color: "BAC7C9", name: "Submarine" },
  { color: "BAEEF9", name: "Charlotte" },
  { color: "BB3385", name: "Medium Red Violet" },
  { color: "BB8983", name: "Brandy Rose" },
  { color: "BBD009", name: "Rio Grande" },
  { color: "BBD7C1", name: "Surf" },
  { color: "BCC9C2", name: "Powder Ash" },
  { color: "BD5E2E", name: "Tuscany" },
  { color: "BD978E", name: "Quicksand" },
  { color: "BDB1A8", name: "Silk" },
  { color: "BDB2A1", name: "Malta" },
  { color: "BDB3C7", name: "Chatelle" },
  { color: "BDBBD7", name: "Lavender Gray" },
  { color: "BDBDC6", name: "French Gray" },
  { color: "BDC8B3", name: "Clay Ash" },
  { color: "BDC9CE", name: "Loblolly" },
  { color: "BDEDFD", name: "French Pass" },
  { color: "BEA6C3", name: "London Hue" },
  { color: "BEB5B7", name: "Pink Swan" },
  { color: "BEDE0D", name: "Fuego" },
  { color: "BF5500", name: "Rose of Sharon" },
  { color: "BFB8B0", name: "Tide" },
  { color: "BFBED8", name: "Blue Haze" },
  { color: "BFC1C2", name: "Silver Sand" },
  { color: "BFC921", name: "Key Lime Pie" },
  { color: "BFDBE2", name: "Ziggurat" },
  { color: "BFFF00", name: "Lime" },
  { color: "C02B18", name: "Thunderbird" },
  { color: "C04737", name: "Mojo" },
  { color: "C08081", name: "Old Rose" },
  { color: "C0C0C0", name: "Silver" },
  { color: "C0D3B9", name: "Pale Leaf" },
  { color: "C0D8B6", name: "Pixie Green" },
  { color: "C1440E", name: "Tia Maria" },
  { color: "C154C1", name: "Fuchsia Pink" },
  { color: "C1A004", name: "Buddha Gold" },
  { color: "C1B7A4", name: "Bison Hide" },
  { color: "C1BAB0", name: "Tea" },
  { color: "C1BECD", name: "Gray Suit" },
  { color: "C1D7B0", name: "Sprout" },
  { color: "C1F07C", name: "Sulu" },
  { color: "C26B03", name: "Indochine" },
  { color: "C2955D", name: "Twine" },
  { color: "C2BDB6", name: "Cotton Seed" },
  { color: "C2CAC4", name: "Pumice" },
  { color: "C2E8E5", name: "Jagged Ice" },
  { color: "C32148", name: "Maroon Flush" },
  { color: "C3B091", name: "Indian Khaki" },
  { color: "C3BFC1", name: "Pale Slate" },
  { color: "C3C3BD", name: "Gray Nickel" },
  { color: "C3CDE6", name: "Periwinkle Gray" },
  { color: "C3D1D1", name: "Tiara" },
  { color: "C3DDF9", name: "Tropical Blue" },
  { color: "C41E3A", name: "Cardinal" },
  { color: "C45655", name: "Fuzzy Wuzzy Brown" },
  { color: "C45719", name: "Orange Roughy" },
  { color: "C4C4BC", name: "Mist Gray" },
  { color: "C4D0B0", name: "Coriander" },
  { color: "C4F4EB", name: "Mint Tulip" },
  { color: "C54B8C", name: "Mulberry" },
  { color: "C59922", name: "Nugget" },
  { color: "C5994B", name: "Tussock" },
  { color: "C5DBCA", name: "Sea Mist" },
  { color: "C5E17A", name: "Yellow Green" },
  { color: "C62D42", name: "Brick Red" },
  { color: "C6726B", name: "Contessa" },
  { color: "C69191", name: "Oriental Pink" },
  { color: "C6A84B", name: "Roti" },
  { color: "C6C3B5", name: "Ash" },
  { color: "C6C8BD", name: "Kangaroo" },
  { color: "C6E610", name: "Las Palmas" },
  { color: "C7031E", name: "Monza" },
  { color: "C71585", name: "Red Violet" },
  { color: "C7BCA2", name: "Coral Reef" },
  { color: "C7C1FF", name: "Melrose" },
  { color: "C7C4BF", name: "Cloud" },
  { color: "C7C9D5", name: "Ghost" },
  { color: "C7CD90", name: "Pine Glade" },
  { color: "C7DDE5", name: "Botticelli" },
  { color: "C88A65", name: "Antique Brass" },
  { color: "C8A2C8", name: "Lilac" },
  { color: "C8A528", name: "Hokey Pokey" },
  { color: "C8AABF", name: "Lily" },
  { color: "C8B568", name: "Laser" },
  { color: "C8E3D7", name: "Edgewater" },
  { color: "C96323", name: "Piper" },
  { color: "C99415", name: "Pizza" },
  { color: "C9A0DC", name: "Light Wisteria" },
  { color: "C9B29B", name: "Rodeo Dust" },
  { color: "C9B35B", name: "Sundance" },
  { color: "C9B93B", name: "Earls Green" },
  { color: "C9C0BB", name: "Silver Rust" },
  { color: "C9D9D2", name: "Conch" },
  { color: "C9FFA2", name: "Reef" },
  { color: "C9FFE5", name: "Aero Blue" },
  { color: "CA3435", name: "Flush Mahogany" },
  { color: "CABB48", name: "Turmeric" },
  { color: "CADCD4", name: "Paris White" },
  { color: "CAE00D", name: "Bitter Lemon" },
  { color: "CAE6DA", name: "Skeptic" },
  { color: "CB8FA9", name: "Viola" },
  { color: "CBCAB6", name: "Foggy Gray" },
  { color: "CBD3B0", name: "Green Mist" },
  { color: "CBDBD6", name: "Nebula" },
  { color: "CC3333", name: "Persian Red" },
  { color: "CC5500", name: "Burnt Orange" },
  { color: "CC7722", name: "Ochre" },
  { color: "CC8899", name: "Puce" },
  { color: "CCCAA8", name: "Thistle Green" },
  { color: "CCCCFF", name: "Periwinkle" },
  { color: "CCFF00", name: "Electric Lime" },
  { color: "CD5700", name: "Tenn" },
  { color: "CD5C5C", name: "Chestnut Rose" },
  { color: "CD8429", name: "Brandy Punch" },
  { color: "CDF4FF", name: "Onahau" },
  { color: "CEB98F", name: "Sorrell Brown" },
  { color: "CEBABA", name: "Cold Turkey" },
  { color: "CEC291", name: "Yuma" },
  { color: "CEC7A7", name: "Chino" },
  { color: "CFA39D", name: "Eunry" },
  { color: "CFB53B", name: "Old Gold" },
  { color: "CFDCCF", name: "Tasman" },
  { color: "CFE5D2", name: "Surf Crest" },
  { color: "CFF9F3", name: "Humming Bird" },
  { color: "CFFAF4", name: "Scandal" },
  { color: "D05F04", name: "Red Stage" },
  { color: "D06DA1", name: "Hopbush" },
  { color: "D07D12", name: "Meteor" },
  { color: "D0BEF8", name: "Perfume" },
  { color: "D0C0E5", name: "Prelude" },
  { color: "D0F0C0", name: "Tea Green" },
  { color: "D18F1B", name: "Geebung" },
  { color: "D1BEA8", name: "Vanilla" },
  { color: "D1C6B4", name: "Soft Amber" },
  { color: "D1D2CA", name: "Celeste" },
  { color: "D1D2DD", name: "Mischka" },
  { color: "D1E231", name: "Pear" },
  { color: "D2691E", name: "Hot Cinnamon" },
  { color: "D27D46", name: "Raw Sienna" },
  { color: "D29EAA", name: "Careys Pink" },
  { color: "D2B48C", name: "Tan" },
  { color: "D2DA97", name: "Deco" },
  { color: "D2F6DE", name: "Blue Romance" },
  { color: "D2F8B0", name: "Gossip" },
  { color: "D3CBBA", name: "Sisal" },
  { color: "D3CDC5", name: "Swirl" },
  { color: "D47494", name: "Charm" },
  { color: "D4B6AF", name: "Clam Shell" },
  { color: "D4BF8D", name: "Straw" },
  { color: "D4C4A8", name: "Akaroa" },
  { color: "D4CD16", name: "Bird Flower" },
  { color: "D4D7D9", name: "Iron" },
  { color: "D4DFE2", name: "Geyser" },
  { color: "D4E2FC", name: "Hawkes Blue" },
  { color: "D54600", name: "Grenadier" },
  { color: "D591A4", name: "Can Can" },
  { color: "D59A6F", name: "Whiskey" },
  { color: "D5D195", name: "Winter Hazel" },
  { color: "D5F6E3", name: "Granny Apple" },
  { color: "D69188", name: "My Pink" },
  { color: "D6C562", name: "Tacha" },
  { color: "D6CEF6", name: "Moon Raker" },
  { color: "D6D6D1", name: "Quill Gray" },
  { color: "D6FFDB", name: "Snowy Mint" },
  { color: "D7837F", name: "New York Pink" },
  { color: "D7C498", name: "Pavlova" },
  { color: "D7D0FF", name: "Fog" },
  { color: "D84437", name: "Valencia" },
  { color: "D87C63", name: "Japonica" },
  { color: "D8BFD8", name: "Thistle" },
  { color: "D8C2D5", name: "Maverick" },
  { color: "D8FCFA", name: "Foam" },
  { color: "D94972", name: "Cabaret" },
  { color: "D99376", name: "Burning Sand" },
  { color: "D9B99B", name: "Cameo" },
  { color: "D9D6CF", name: "Timberwolf" },
  { color: "D9DCC1", name: "Tana" },
  { color: "D9E4F5", name: "Link Water" },
  { color: "D9F7FF", name: "Mabel" },
  { color: "DA3287", name: "Cerise" },
  { color: "DA5B38", name: "Flame Pea" },
  { color: "DA6304", name: "Bamboo" },
  { color: "DA6A41", name: "Red Damask" },
  { color: "DA70D6", name: "Orchid" },
  { color: "DA8A67", name: "Copperfield" },
  { color: "DAA520", name: "Golden Grass" },
  { color: "DAECD6", name: "Zanah" },
  { color: "DAF4F0", name: "Iceberg" },
  { color: "DAFAFF", name: "Oyster Bay" },
  { color: "DB5079", name: "Cranberry" },
  { color: "DB9690", name: "Petite Orchid" },
  { color: "DB995E", name: "Di Serria" },
  { color: "DBDBDB", name: "Alto" },
  { color: "DBFFF8", name: "Frosted Mint" },
  { color: "DC143C", name: "Crimson" },
  { color: "DC4333", name: "Punch" },
  { color: "DCB20C", name: "Galliano" },
  { color: "DCB4BC", name: "Blossom" },
  { color: "DCD747", name: "Wattle" },
  { color: "DCD9D2", name: "Westar" },
  { color: "DCDDCC", name: "Moon Mist" },
  { color: "DCEDB4", name: "Caper" },
  { color: "DCF0EA", name: "Swans Down" },
  { color: "DDD6D5", name: "Swiss Coffee" },
  { color: "DDF9F1", name: "White Ice" },
  { color: "DE3163", name: "Cerise Red" },
  { color: "DE6360", name: "Roman" },
  { color: "DEA681", name: "Tumbleweed" },
  { color: "DEBA13", name: "Gold Tips" },
  { color: "DEC196", name: "Brandy" },
  { color: "DECBC6", name: "Wafer" },
  { color: "DED4A4", name: "Sapling" },
  { color: "DED717", name: "Barberry" },
  { color: "DEE5C0", name: "Beryl Green" },
  { color: "DEF5FF", name: "Pattens Blue" },
  { color: "DF73FF", name: "Heliotrope" },
  { color: "DFBE6F", name: "Apache" },
  { color: "DFCD6F", name: "Chenin" },
  { color: "DFCFDB", name: "Lola" },
  { color: "DFECDA", name: "Willow Brook" },
  { color: "DFFF00", name: "Chartreuse Yellow" },
  { color: "E0B0FF", name: "Mauve" },
  { color: "E0B646", name: "Anzac" },
  { color: "E0B974", name: "Harvest Gold" },
  { color: "E0C095", name: "Calico" },
  { color: "E0FFFF", name: "Baby Blue" },
  { color: "E16865", name: "Sunglo" },
  { color: "E1BC64", name: "Equator" },
  { color: "E1C0C8", name: "Pink Flare" },
  { color: "E1E6D6", name: "Periglacial Blue" },
  { color: "E1EAD4", name: "Kidnapper" },
  { color: "E1F6E8", name: "Tara" },
  { color: "E25465", name: "Mandy" },
  { color: "E2725B", name: "Terracotta" },
  { color: "E28913", name: "Golden Bell" },
  { color: "E292C0", name: "Shocking" },
  { color: "E29418", name: "Dixie" },
  { color: "E29CD2", name: "Light Orchid" },
  { color: "E2D8ED", name: "Snuff" },
  { color: "E2EBED", name: "Mystic" },
  { color: "E2F3EC", name: "Apple Green" },
  { color: "E30B5C", name: "Razzmatazz" },
  { color: "E32636", name: "Alizarin Crimson" },
  { color: "E34234", name: "Cinnabar" },
  { color: "E3BEBE", name: "Cavern Pink" },
  { color: "E3F5E1", name: "Peppermint" },
  { color: "E3F988", name: "Mindaro" },
  { color: "E47698", name: "Deep Blush" },
  { color: "E49B0F", name: "Gamboge" },
  { color: "E4C2D5", name: "Melanie" },
  { color: "E4CFDE", name: "Twilight" },
  { color: "E4D1C0", name: "Bone" },
  { color: "E4D422", name: "Sunflower" },
  { color: "E4D5B7", name: "Grain Brown" },
  { color: "E4D69B", name: "Zombie" },
  { color: "E4F6E7", name: "Frostee" },
  { color: "E4FFD1", name: "Snow Flurry" },
  { color: "E52B50", name: "Amaranth" },
  { color: "E5841B", name: "Zest" },
  { color: "E5CCC9", name: "Dust Storm" },
  { color: "E5D7BD", name: "Stark White" },
  { color: "E5D8AF", name: "Hampton" },
  { color: "E5E0E1", name: "Bon Jour" },
  { color: "E5E5E5", name: "Mercury" },
  { color: "E5F9F6", name: "Polar" },
  { color: "E64E03", name: "Trinidad" },
  { color: "E6BE8A", name: "Gold Sand" },
  { color: "E6BEA5", name: "Cashmere" },
  { color: "E6D7B9", name: "Double Spanish White" },
  { color: "E6E4D4", name: "Satin Linen" },
  { color: "E6F2EA", name: "Harp" },
  { color: "E6F8F3", name: "Off Green" },
  { color: "E6FFE9", name: "Hint of Green" },
  { color: "E6FFFF", name: "Tranquil" },
  { color: "E77200", name: "Mango Tango" },
  { color: "E7730A", name: "Christine" },
  { color: "E79F8C", name: "Tonys Pink" },
  { color: "E79FC4", name: "Kobi" },
  { color: "E7BCB4", name: "Rose Fog" },
  { color: "E7BF05", name: "Corn" },
  { color: "E7CD8C", name: "Putty" },
  { color: "E7ECE6", name: "Gray Nurse" },
  { color: "E7F8FF", name: "Lily White" },
  { color: "E7FEFF", name: "Bubbles" },
  { color: "E89928", name: "Fire Bush" },
  { color: "E8B9B3", name: "Shilo" },
  { color: "E8E0D5", name: "Pearl Bush" },
  { color: "E8EBE0", name: "Green White" },
  { color: "E8F1D4", name: "Chrome White" },
  { color: "E8F2EB", name: "Gin" },
  { color: "E8F5F2", name: "Aqua Squeeze" },
  { color: "E96E00", name: "Clementine" },
  { color: "E97451", name: "Burnt Sienna" },
  { color: "E97C07", name: "Tahiti Gold" },
  { color: "E9CECD", name: "Oyster Pink" },
  { color: "E9D75A", name: "Confetti" },
  { color: "E9E3E3", name: "Ebb" },
  { color: "E9F8ED", name: "Ottoman" },
  { color: "E9FFFD", name: "Clear Day" },
  { color: "EA88A8", name: "Carissma" },
  { color: "EAAE69", name: "Porsche" },
  { color: "EAB33B", name: "Tulip Tree" },
  { color: "EAC674", name: "Rob Roy" },
  { color: "EADAB8", name: "Raffia" },
  { color: "EAE8D4", name: "White Rock" },
  { color: "EAF6EE", name: "Panache" },
  { color: "EAF6FF", name: "Solitude" },
  { color: "EAF9F5", name: "Aqua Spring" },
  { color: "EAFFFE", name: "Dew" },
  { color: "EB9373", name: "Apricot" },
  { color: "EBC2AF", name: "Zinnwaldite" },
  { color: "ECA927", name: "Fuel Yellow" },
  { color: "ECC54E", name: "Ronchi" },
  { color: "ECC7EE", name: "French Lilac" },
  { color: "ECCDB9", name: "Just Right" },
  { color: "ECE090", name: "Wild Rice" },
  { color: "ECEBBD", name: "Fall Green" },
  { color: "ECEBCE", name: "Aths Special" },
  { color: "ECF245", name: "Starship" },
  { color: "ED0A3F", name: "Red Ribbon" },
  { color: "ED7A1C", name: "Tango" },
  { color: "ED9121", name: "Carrot Orange" },
  { color: "ED989E", name: "Sea Pink" },
  { color: "EDB381", name: "Tacao" },
  { color: "EDC9AF", name: "Desert Sand" },
  { color: "EDCDAB", name: "Pancho" },
  { color: "EDDCB1", name: "Chamois" },
  { color: "EDEA99", name: "Primrose" },
  { color: "EDF5DD", name: "Frost" },
  { color: "EDF5F5", name: "Aqua Haze" },
  { color: "EDF6FF", name: "Zumthor" },
  { color: "EDF9F1", name: "Narvik" },
  { color: "EDFC84", name: "Honeysuckle" },
  { color: "EE82EE", name: "Lavender Magenta" },
  { color: "EEC1BE", name: "Beauty Bush" },
  { color: "EED794", name: "Chalky" },
  { color: "EED9C4", name: "Almond" },
  { color: "EEDC82", name: "Flax" },
  { color: "EEDEDA", name: "Bizarre" },
  { color: "EEE3AD", name: "Double Colonial White" },
  { color: "EEEEE8", name: "Cararra" },
  { color: "EEEF78", name: "Manz" },
  { color: "EEF0C8", name: "Tahuna Sands" },
  { color: "EEF0F3", name: "Athens Gray" },
  { color: "EEF3C3", name: "Tusk" },
  { color: "EEF4DE", name: "Loafer" },
  { color: "EEF6F7", name: "Catskill White" },
  { color: "EEFDFF", name: "Twilight Blue" },
  { color: "EEFF9A", name: "Jonquil" },
  { color: "EEFFE2", name: "Rice Flower" },
  { color: "EF863F", name: "Jaffa" },
  { color: "EFEFEF", name: "Gallery" },
  { color: "EFF2F3", name: "Porcelain" },
  { color: "F091A9", name: "Mauvelous" },
  { color: "F0D52D", name: "Golden Dream" },
  { color: "F0DB7D", name: "Golden Sand" },
  { color: "F0DC82", name: "Buff" },
  { color: "F0E2EC", name: "Prim" },
  { color: "F0E68C", name: "Khaki" },
  { color: "F0EEFD", name: "Selago" },
  { color: "F0EEFF", name: "Titan White" },
  { color: "F0F8FF", name: "Alice Blue" },
  { color: "F0FCEA", name: "Feta" },
  { color: "F18200", name: "Gold Drop" },
  { color: "F19BAB", name: "Wewak" },
  { color: "F1E788", name: "Sahara Sand" },
  { color: "F1E9D2", name: "Parchment" },
  { color: "F1E9FF", name: "Blue Chalk" },
  { color: "F1EEC1", name: "Mint Julep" },
  { color: "F1F1F1", name: "Seashell" },
  { color: "F1F7F2", name: "Saltpan" },
  { color: "F1FFAD", name: "Tidal" },
  { color: "F1FFC8", name: "Chiffon" },
  { color: "F2552A", name: "Flamingo" },
  { color: "F28500", name: "Tangerine" },
  { color: "F2C3B2", name: "Mandys Pink" },
  { color: "F2F2F2", name: "Concrete" },
  { color: "F2FAFA", name: "Black Squeeze" },
  { color: "F34723", name: "Pomegranate" },
  { color: "F3AD16", name: "Buttercup" },
  { color: "F3D69D", name: "New Orleans" },
  { color: "F3D9DF", name: "Vanilla Ice" },
  { color: "F3E7BB", name: "Sidecar" },
  { color: "F3E9E5", name: "Dawn Pink" },
  { color: "F3EDCF", name: "Wheatfield" },
  { color: "F3FB62", name: "Canary" },
  { color: "F3FBD4", name: "Orinoco" },
  { color: "F3FFD8", name: "Carla" },
  { color: "F400A1", name: "Hollywood Cerise" },
  { color: "F4A460", name: "Sandy brown" },
  { color: "F4C430", name: "Saffron" },
  { color: "F4D81C", name: "Ripe Lemon" },
  { color: "F4EBD3", name: "Janna" },
  { color: "F4F2EE", name: "Pampas" },
  { color: "F4F4F4", name: "Wild Sand" },
  { color: "F4F8FF", name: "Zircon" },
  { color: "F57584", name: "Froly" },
  { color: "F5C85C", name: "Cream Can" },
  { color: "F5C999", name: "Manhattan" },
  { color: "F5D5A0", name: "Maize" },
  { color: "F5DEB3", name: "Wheat" },
  { color: "F5E7A2", name: "Sandwisp" },
  { color: "F5E7E2", name: "Pot Pourri" },
  { color: "F5E9D3", name: "Albescent White" },
  { color: "F5EDEF", name: "Soft Peach" },
  { color: "F5F3E5", name: "Ecru White" },
  { color: "F5F5DC", name: "Beige" },
  { color: "F5FB3D", name: "Golden Fizz" },
  { color: "F5FFBE", name: "Australian Mint" },
  { color: "F64A8A", name: "French Rose" },
  { color: "F653A6", name: "Brilliant Rose" },
  { color: "F6A4C9", name: "Illusion" },
  { color: "F6F0E6", name: "Merino" },
  { color: "F6F7F7", name: "Black Haze" },
  { color: "F6FFDC", name: "Spring Sun" },
  { color: "F7468A", name: "Violet Red" },
  { color: "F77703", name: "Chilean Fire" },
  { color: "F77FBE", name: "Persian Pink" },
  { color: "F7B668", name: "Rajah" },
  { color: "F7C8DA", name: "Azalea" },
  { color: "F7DBE6", name: "We Peep" },
  { color: "F7F2E1", name: "Quarter Spanish White" },
  { color: "F7F5FA", name: "Whisper" },
  { color: "F7FAF7", name: "Snow Drift" },
  { color: "F8B853", name: "Casablanca" },
  { color: "F8C3DF", name: "Chantilly" },
  { color: "F8D9E9", name: "Cherub" },
  { color: "F8DB9D", name: "Marzipan" },
  { color: "F8DD5C", name: "Energy Yellow" },
  { color: "F8E4BF", name: "Givry" },
  { color: "F8F0E8", name: "White Linen" },
  { color: "F8F4FF", name: "Magnolia" },
  { color: "F8F6F1", name: "Spring Wood" },
  { color: "F8F7DC", name: "Coconut Cream" },
  { color: "F8F7FC", name: "White Lilac" },
  { color: "F8F8F7", name: "Desert Storm" },
  { color: "F8F99C", name: "Texas" },
  { color: "F8FACD", name: "Corn Field" },
  { color: "F8FDD3", name: "Mimosa" },
  { color: "F95A61", name: "Carnation" },
  { color: "F9BF58", name: "Saffron Mango" },
  { color: "F9E0ED", name: "Carousel Pink" },
  { color: "F9E4BC", name: "Dairy Cream" },
  { color: "F9E663", name: "Portica" },
  { color: "F9EAF3", name: "Amour" },
  { color: "F9F8E4", name: "Rum Swizzle" },
  { color: "F9FF8B", name: "Dolly" },
  { color: "F9FFF6", name: "Sugar Cane" },
  { color: "FA7814", name: "Ecstasy" },
  { color: "FA9D5A", name: "Tan Hide" },
  { color: "FAD3A2", name: "Corvette" },
  { color: "FADFAD", name: "Peach Yellow" },
  { color: "FAE600", name: "Turbo" },
  { color: "FAEAB9", name: "Astra" },
  { color: "FAECCC", name: "Champagne" },
  { color: "FAF0E6", name: "Linen" },
  { color: "FAF3F0", name: "Fantasy" },
  { color: "FAF7D6", name: "Citrine White" },
  { color: "FAFAFA", name: "Alabaster" },
  { color: "FAFDE4", name: "Hint of Yellow" },
  { color: "FAFFA4", name: "Milan" },
  { color: "FB607F", name: "Brink Pink" },
  { color: "FB8989", name: "Geraldine" },
  { color: "FBA0E3", name: "Lavender Rose" },
  { color: "FBA129", name: "Sea Buckthorn" },
  { color: "FBAC13", name: "Sun" },
  { color: "FBAED2", name: "Lavender Pink" },
  { color: "FBB2A3", name: "Rose Bud" },
  { color: "FBBEDA", name: "Cupid" },
  { color: "FBCCE7", name: "Classic Rose" },
  { color: "FBCEB1", name: "Apricot Peach" },
  { color: "FBE7B2", name: "Banana Mania" },
  { color: "FBE870", name: "Marigold Yellow" },
  { color: "FBE96C", name: "Festival" },
  { color: "FBEA8C", name: "Sweet Corn" },
  { color: "FBEC5D", name: "Candy Corn" },
  { color: "FBF9F9", name: "Hint of Red" },
  { color: "FBFFBA", name: "Shalimar" },
  { color: "FC0FC0", name: "Shocking Pink" },
  { color: "FC80A5", name: "Tickle Me Pink" },
  { color: "FC9C1D", name: "Tree Poppy" },
  { color: "FCC01E", name: "Lightning Yellow" },
  { color: "FCD667", name: "Goldenrod" },
  { color: "FCD917", name: "Candlelight" },
  { color: "FCDA98", name: "Cherokee" },
  { color: "FCF4D0", name: "Double Pearl Lusta" },
  { color: "FCF4DC", name: "Pearl Lusta" },
  { color: "FCF8F7", name: "Vista White" },
  { color: "FCFBF3", name: "Bianca" },
  { color: "FCFEDA", name: "Moon Glow" },
  { color: "FCFFE7", name: "China Ivory" },
  { color: "FCFFF9", name: "Ceramic" },
  { color: "FD0E35", name: "Torch Red" },
  { color: "FD5B78", name: "Wild Watermelon" },
  { color: "FD7B33", name: "Crusta" },
  { color: "FD7C07", name: "Sorbus" },
  { color: "FD9FA2", name: "Sweet Pink" },
  { color: "FDD5B1", name: "Light Apricot" },
  { color: "FDD7E4", name: "Pig Pink" },
  { color: "FDE1DC", name: "Cinderella" },
  { color: "FDE295", name: "Golden Glow" },
  { color: "FDE910", name: "Lemon" },
  { color: "FDF5E6", name: "Old Lace" },
  { color: "FDF6D3", name: "Half Colonial White" },
  { color: "FDF7AD", name: "Drover" },
  { color: "FDFEB8", name: "Pale Prim" },
  { color: "FDFFD5", name: "Cumulus" },
  { color: "FE28A2", name: "Persian Rose" },
  { color: "FE4C40", name: "Sunset Orange" },
  { color: "FE6F5E", name: "Bittersweet" },
  { color: "FE9D04", name: "California" },
  { color: "FEA904", name: "Yellow Sea" },
  { color: "FEBAAD", name: "Melon" },
  { color: "FED33C", name: "Bright Sun" },
  { color: "FED85D", name: "Dandelion" },
  { color: "FEDB8D", name: "Salomie" },
  { color: "FEE5AC", name: "Cape Honey" },
  { color: "FEEBF3", name: "Remy" },
  { color: "FEEFCE", name: "Oasis" },
  { color: "FEF0EC", name: "Bridesmaid" },
  { color: "FEF2C7", name: "Beeswax" },
  { color: "FEF3D8", name: "Bleach White" },
  { color: "FEF4CC", name: "Pipi" },
  { color: "FEF4DB", name: "Half Spanish White" },
  { color: "FEF4F8", name: "Wisp Pink" },
  { color: "FEF5F1", name: "Provincial Pink" },
  { color: "FEF7DE", name: "Half Dutch White" },
  { color: "FEF8E2", name: "Solitaire" },
  { color: "FEF8FF", name: "White Pointer" },
  { color: "FEF9E3", name: "Off Yellow" },
  { color: "FEFCED", name: "Orange White" },
  { color: "FF0000", name: "Red" },
  { color: "FF007F", name: "Rose" },
  { color: "FF00CC", name: "Purple Pizzazz" },
  { color: "FF00FF", name: "Magenta / Fuchsia" },
  { color: "FF2400", name: "Scarlet" },
  { color: "FF3399", name: "Wild Strawberry" },
  { color: "FF33CC", name: "Razzle Dazzle Rose" },
  { color: "FF355E", name: "Radical Red" },
  { color: "FF3F34", name: "Red Orange" },
  { color: "FF4040", name: "Coral Red" },
  { color: "FF4D00", name: "Vermilion" },
  { color: "FF4F00", name: "International Orange" },
  { color: "FF6037", name: "Outrageous Orange" },
  { color: "FF6600", name: "Blaze Orange" },
  { color: "FF66FF", name: "Pink Flamingo" },
  { color: "FF681F", name: "Orange" },
  { color: "FF69B4", name: "Hot Pink" },
  { color: "FF6B53", name: "Persimmon" },
  { color: "FF6FFF", name: "Blush Pink" },
  { color: "FF7034", name: "Burning Orange" },
  { color: "FF7518", name: "Pumpkin" },
  { color: "FF7D07", name: "Flamenco" },
  { color: "FF7F00", name: "Flush Orange" },
  { color: "FF7F50", name: "Coral" },
  { color: "FF8C69", name: "Salmon" },
  { color: "FF9000", name: "Pizazz" },
  { color: "FF910F", name: "West Side" },
  { color: "FF91A4", name: "Pink Salmon" },
  { color: "FF9933", name: "Neon Carrot" },
  { color: "FF9966", name: "Atomic Tangerine" },
  { color: "FF9980", name: "Vivid Tangerine" },
  { color: "FF9E2C", name: "Sunshade" },
  { color: "FFA000", name: "Orange Peel" },
  { color: "FFA194", name: "Mona Lisa" },
  { color: "FFA500", name: "Web Orange" },
  { color: "FFA6C9", name: "Carnation Pink" },
  { color: "FFAB81", name: "Hit Pink" },
  { color: "FFAE42", name: "Yellow Orange" },
  { color: "FFB0AC", name: "Cornflower Lilac" },
  { color: "FFB1B3", name: "Sundown" },
  { color: "FFB31F", name: "My Sin" },
  { color: "FFB555", name: "Texas Rose" },
  { color: "FFB7D5", name: "Cotton Candy" },
  { color: "FFB97B", name: "Macaroni and Cheese" },
  { color: "FFBA00", name: "Selective Yellow" },
  { color: "FFBD5F", name: "Koromiko" },
  { color: "FFBF00", name: "Amber" },
  { color: "FFC0A8", name: "Wax Flower" },
  { color: "FFC0CB", name: "Pink" },
  { color: "FFC3C0", name: "Your Pink" },
  { color: "FFC901", name: "Supernova" },
  { color: "FFCBA4", name: "Flesh" },
  { color: "FFCC33", name: "Sunglow" },
  { color: "FFCC5C", name: "Golden Tainoi" },
  { color: "FFCC99", name: "Peach Orange" },
  { color: "FFCD8C", name: "Chardonnay" },
  { color: "FFD1DC", name: "Pastel Pink" },
  { color: "FFD2B7", name: "Romantic" },
  { color: "FFD38C", name: "Grandis" },
  { color: "FFD700", name: "Gold" },
  { color: "FFD800", name: "School bus Yellow" },
  { color: "FFD8D9", name: "Cosmos" },
  { color: "FFDB58", name: "Mustard" },
  { color: "FFDCD6", name: "Peach Schnapps" },
  { color: "FFDDAF", name: "Caramel" },
  { color: "FFDDCD", name: "Tuft Bush" },
  { color: "FFDDCF", name: "Watusi" },
  { color: "FFDDF4", name: "Pink Lace" },
  { color: "FFDEAD", name: "Navajo White" },
  { color: "FFDEB3", name: "Frangipani" },
  { color: "FFE1DF", name: "Pippin" },
  { color: "FFE1F2", name: "Pale Rose" },
  { color: "FFE2C5", name: "Negroni" },
  { color: "FFE5A0", name: "Cream Brulee" },
  { color: "FFE5B4", name: "Peach" },
  { color: "FFE6C7", name: "Tequila" },
  { color: "FFE772", name: "Kournikova" },
  { color: "FFEAC8", name: "Sandy Beach" },
  { color: "FFEAD4", name: "Karry" },
  { color: "FFEC13", name: "Broom" },
  { color: "FFEDBC", name: "Colonial White" },
  { color: "FFEED8", name: "Derby" },
  { color: "FFEFA1", name: "Vis Vis" },
  { color: "FFEFC1", name: "Egg White" },
  { color: "FFEFD5", name: "Papaya Whip" },
  { color: "FFEFEC", name: "Fair Pink" },
  { color: "FFF0DB", name: "Peach Cream" },
  { color: "FFF0F5", name: "Lavender blush" },
  { color: "FFF14F", name: "Gorse" },
  { color: "FFF1B5", name: "Buttermilk" },
  { color: "FFF1D8", name: "Pink Lady" },
  { color: "FFF1EE", name: "Forget Me Not" },
  { color: "FFF1F9", name: "Tutu" },
  { color: "FFF39D", name: "Picasso" },
  { color: "FFF3F1", name: "Chardon" },
  { color: "FFF46E", name: "Paris Daisy" },
  { color: "FFF4CE", name: "Barley White" },
  { color: "FFF4DD", name: "Egg Sour" },
  { color: "FFF4E0", name: "Sazerac" },
  { color: "FFF4E8", name: "Serenade" },
  { color: "FFF4F3", name: "Chablis" },
  { color: "FFF5EE", name: "Seashell Peach" },
  { color: "FFF5F3", name: "Sauvignon" },
  { color: "FFF6D4", name: "Milk Punch" },
  { color: "FFF6DF", name: "Varden" },
  { color: "FFF6F5", name: "Rose White" },
  { color: "FFF8D1", name: "Baja White" },
  { color: "FFF9E2", name: "Gin Fizz" },
  { color: "FFF9E6", name: "Early Dawn" },
  { color: "FFFACD", name: "Lemon Chiffon" },
  { color: "FFFAF4", name: "Bridal Heath" },
  { color: "FFFBDC", name: "Scotch Mist" },
  { color: "FFFBF9", name: "Soapstone" },
  { color: "FFFC99", name: "Witch Haze" },
  { color: "FFFCEA", name: "Buttery White" },
  { color: "FFFCEE", name: "Island Spice" },
  { color: "FFFDD0", name: "Cream" },
  { color: "FFFDE6", name: "Chilean Heath" },
  { color: "FFFDE8", name: "Travertine" },
  { color: "FFFDF3", name: "Orchid White" },
  { color: "FFFDF4", name: "Quarter Pearl Lusta" },
  { color: "FFFEE1", name: "Half and Half" },
  { color: "FFFEEC", name: "Apricot White" },
  { color: "FFFEF0", name: "Rice Cake" },
  { color: "FFFEF6", name: "Black White" },
  { color: "FFFEFD", name: "Romance" },
  { color: "FFFF00", name: "Yellow" },
  { color: "FFFF66", name: "Laser Lemon" },
  { color: "FFFF99", name: "Pale Canary" },
  { color: "FFFFB4", name: "Portafino" },
  { color: "FFFFF0", name: "Ivory" },
]

module.exports = colors;
